### ISSUE TITLE
Random thoughts

### ISSUE THREAD

**Issue by sandstrom** [kviklet/kviklet#74]
I think this is a great idea:
- Add BSL or a similar license
- To monetize, I'd avoid using a "hosted version", because people want to run this themselves, for security. Instead, I'd hide advanced features behind an enterprise license (can still be open source in the sense that you'll have it on Github etc, larger companies will respect any agreement, so no need to worry about having it open).
- Add support for Github IDP (or ideally just any OIDC)
- Add support for 'code consoles', such as `rails console`.
- Maybe just regular bash console too (fake ssh over HTTP), we'd find that very useful.
- Probably too late, but I'd consider another language than Kotlin. We avoid deploying products in the Java ecosystem. So much more work compared to something written in e.g. Go, Rust or C++.

**Comment by Askir** [comment]
Hey, thanks a lot for the input!
I'm gonna go through this one by one:
> Add BSL or a similar license

Simply went with MIT since I plan to just continue this as a side project for now. But if we do release an enterprise version again we will change this.

> To monetize, I'd avoid using a "hosted version", because people want to run this themselves, for security. Instead, I'd hide advanced features behind an enterprise license (can still be open source in the sense that you'll have it on Github etc, larger companies will respect any agreement, so no need to worry about having it open).

Yes no plans for a hosted version, fully agreed here.

> Add support for Github IDP (or ideally just any OIDC)

Should actually already work but didn't put it in the readme because I haven't tried it yet.

> Add support for 'code consoles', such as rails console.
Maybe just regular bash console too (fake ssh over HTTP), we'd find that very useful.

This is something we've considered but we want to focus on database access for now. Branching out on other tools (consoles, kubernetes, ssh) would mean a bit of an explosion in features and bringing that all into one product without making it messy and hard to understand is very complex. Also I wouldn't know with what to start since the field is so large. I would be happy to build a POC though for rails if that's what you want to try? If it works well we can then consider adapting the tool into that direction.

> Probably too late, but I'd consider another language than Kotlin. We avoid deploying products in the Java ecosystem. So much more work compared to something written in e.g. Go, Rust or C++.

Fair, since it's a docker container I would hope it isn't such a big deal, we mainly chose kotlin because we think that the JDBC drivers are the most mature db drivers out there and wanted to take advantage of that. I have fought a fair share myself though and would love to learn some Rust some time. So I might try a backend rewrite at some point. Not any time soon though 😅 

Overall we tried bringing this to market for a few weeks but the feedback was generally that there is not enough willingness to pay so I am putting it out as open source for now and will just try to maintain it in my free time. Maybe at some point we have the traction to grow it into a business though!

**Comment by IR-DAN** [comment]
Thanks for this!! 🚀

**Comment by sandstrom** [comment]
> Fair, since it's a docker container I would hope it isn't such a big deal,

Valid point!

> This is something we've considered but we want to focus on database access for now. Branching out on other tools (consoles, kubernetes, ssh) would mean a bit of an explosion in features and bringing that all into one product without making it messy and hard to understand is very complex.

Makes sense!

I think DB access in itself, is probably a valid niche. I wouldn't expand at this point.

### Misc

I know at least Stripe has some kind of internal tool along these lines:

https://news.ycombinator.com/item?id=10365798

(the original post mortem isn't to be found, but it's also mentioned in the comments)

**Comment by dc-95** [comment]
> Hey, thanks a lot for the input! I'm gonna go through this one by one:
> 
> > Add BSL or a similar license
> 
> Simply went with MIT since I plan to just continue this as a side project for now. But if we do release an enterprise version again we will change this.
> 
> > To monetize, I'd avoid using a "hosted version", because people want to run this themselves, for security. Instead, I'd hide advanced features behind an enterprise license (can still be open source in the sense that you'll have it on Github etc, larger companies will respect any agreement, so no need to worry about having it open).
> 
> Yes no plans for a hosted version, fully agreed here.
> 
> > Add support for Github IDP (or ideally just any OIDC)
> 
> Should actually already work but didn't put it in the readme because I haven't tried it yet.
> 
> > Add support for 'code consoles', such as rails console.
> > Maybe just regular bash console too (fake ssh over HTTP), we'd find that very useful.
> 
> This is something we've considered but we want to focus on database access for now. Branching out on other tools (consoles, kubernetes, ssh) would mean a bit of an explosion in features and bringing that all into one product without making it messy and hard to understand is very complex. Also I wouldn't know with what to start since the field is so large. I would be happy to build a POC though for rails if that's what you want to try? If it works well we can then consider adapting the tool into that direction.
> 
> > Probably too late, but I'd consider another language than Kotlin. We avoid deploying products in the Java ecosystem. So much more work compared to something written in e.g. Go, Rust or C++.
> 
> Fair, since it's a docker container I would hope it isn't such a big deal, we mainly chose kotlin because we think that the JDBC drivers are the most mature db drivers out there and wanted to take advantage of that. I have fought a fair share myself though and would love to learn some Rust some time. So I might try a backend rewrite at some point. Not any time soon though 😅
> 
> Overall we tried bringing this to market for a few weeks but the feedback was generally that there is not enough willingness to pay so I am putting it out as open source for now and will just try to maintain it in my free time. Maybe at some point we have the traction to grow it into a business though!

+1 PoC for rails

**Comment by Askir** [comment]
@dc-95 How do you currently run any rails commands? Are you hosting your RoR code in containers via kubernetes?
Or more barebones in VMs? How do you currently access it?

My first thought would be to build a kubernetes integration e.g. allow running some sort of kubectl exec on containers, so you could run your rails commands that way. Would this help?

**Comment by Askir** [comment]
@sandstrom same question to you if you have some time to go in detail about your current setup  :)

**Comment by misterek** [comment]
I'll just chime in that an interesting place to look would be: https://github.com/gravitational/teleport

They recently announced a license change that'll make it harder for some folks to use, so I suspect some people will be looking at other options.

IMHO, I think being able to run kubectl as a way to run a console is a great idea.  

I really love the approval of running sql, and think it's a great idea that you're expanding.  I'd love to help but Kotlin isn't exactly in my wheelhouse.

**Comment by sandstrom** [comment]
> How do you currently run any rails commands? Are you hosting your RoR code in containers via kubernetes? Or more barebones in VMs? How do you currently access it?

EC2 VMs, running docker (without kubernetes)

> My first thought would be to build a kubernetes integration e.g. allow running some sort of kubectl exec on containers, so you could run your rails commands that way. Would this help?

I'd say your solution should be agnostic on how to connect, so it might be `ssh` + `docker compose exec …`, or it might be `wiregurad` + `kubectl`, or it might be something else.

**Comment by Askir** [comment]
> I'll just chime in that an interesting place to look would be: https://github.com/gravitational/teleport
> 
> They recently announced a license change that'll make it harder for some folks to use, so I suspect some people will be looking at other options.

Thanks, I know about teleport and the license change. I always found it a bit like shooting with nukes at ants anyways, with a separate cluster etc. I think running a simple container should be more than enough.

I thought kubernetes and ssh in general could wait a bit but since multiple people are requesting it here, I should probably invest into it.

**Comment by Askir** [comment]
Currently I have one connection type for SQL databases (mysql and postgres).

For any sort of bash access I'd add another type of connection that allows running shell commands. Now I wonder though if it makes sense to even have a single statement execution for that? Or if in a shell you will always run multiple statements anyways so you just need the temporary accessed live session?
Also if I forward all log output to the frontend, it might potentially get quite long but I guess for an initial version that is fine.

@sandstrom 
I think I can add both an option to run `docker-compose exec` and `kubectl exec` in some capacity then.

Any additional VPN or Jump hosting has to be on another level below this because it would also necessary for the DB connection types.
I am currently assuming that any user is running Kviklet directly in the same network as the desired infrastructure.

Running single commands and providing their output sounds a lot easier than having an actual interactive shell though. Which is what you need for a `rails console` or `django shell`. But it might be a good starting point anyways.

**Comment by sandstrom** [comment]
> Now I wonder though if it makes sense to even have a single statement execution for that? Or if in a shell you will always run multiple statements anyways so you just need the temporary accessed live session?

I think single-state execution make sens for some things, e.g. asking for permission/review before writing committing a change to a DB index, or make some other operation. But other times, it will be better to ask for 'temporary access for X hours', with just a log being saved, but no approval for every statement/line.

> Any additional VPN or Jump hosting has to be on another level below this because it would also necessary for the DB connection types. I am currently assuming that any user is running Kviklet directly in the same network as the desired infrastructure.

I think this is a good assumption, and I'm not saying Kviklet should handle jump hosts necessarily, but it need to taken into account, such that Kviklet can be made to work in such an environment.

**Comment by Askir** [comment]
> I think this is a good assumption, and I'm not saying Kviklet should handle jump hosts necessarily

I might add it eventually but just separating it for now from the "let me run some bash commands" feature request as I think it's a different beast.

**Comment by Askir** [comment]
Just fyi: working on a kubernetes integration (like kubectl exec) in #83 now.
Will still take a week or two before I have a mergeable first version though.

Will look at docker compose afterwards.

**Comment by Askir** [comment]
I just merged the initial kubernetes integration in #83. You can now create Requests that contain a single command like in `kubectl exec` and go through the same flow as with database connections.

I experimented a bit with websockets and think I can use them to build an interactive terminal so you can start shells (like the original request). It's not super easy though as I have to transmit individual keystrokes and find a decent terminal component for the frontend.
And also... I'm not quite sure yet how the audit logging will work with that since I will no longer have individual commands that I can save as a separate audit entry. Might have to do some fancy parsing or just save the whole sessions as a single entry...

**Comment by sapisuper** [comment]
Hi is there any detail documentation regarding OIDC ? far as I know only support Google SSO and Keycloak

**Comment by Askir** [comment]
@sapisuper There is currently no logout button. Sessions last 30 minutes which is the spring security default. If you want to login as a different use you can go to /login and do so though.

OIDC-wise I haven't tried any other provider yet. But in theory it should work the same way as keycloak, I think. Meaning you'd have to provide the same Environment variables. Which one do you want to use?

**Comment by VIDGuide** [comment]
I'd be keen on setting up AzureAD SSO, so SAML or OIDC would work. I'll have to try it out and see how it goes.

**Comment by Askir** [comment]
Let me know if you run into any issues!

**Comment by sapisuper** [comment]
@VIDGuide can you share your variable used it 😄 . I tried use this variable but doesn't work in gitlab SSO : 
KVIKLET_IDENTITY_PROVIDER_CLIENT_ID: [value clientId]
KVIKLET_IDENTITY_PROVIDER_CLIENT_SECRET: [value clientSecret]
KVIKLET_IDENTITY_PROVIDER_TYPE: gitlab
KVIKLET_IDENTITY_PROVIDER_ISSUER_URI: https://[host gitlab] 

@Askir Thanks for the information, let me note regarding /login 👍

**Comment by Askir** [comment]
@sapisuper I checked again, and there is actually a few points where I hardcoded google and Keycloak although it shouldn't really be necessary. I'll try to fix those so that you can use any OIDC provider. Sorry for the confusion.

**Comment by Askir** [comment]
Okay I merged #120 maybe you can try again? I don't really have a gitlab account, and would like to avoid going through the hassle of setting one up :D
I set issuer-uri locally to simply https://gitlab.com and it at least redirects to the gitlab login that way. But ofc doesn't go further without an actual working client-id and secret. I didn't find any docs on the issuer uri on the gitlab page, I kinda thought the OIDC standard would be followed more strictly. If setting the issuerURI doesn't work for you I might have to allow setting the `authorization_endpoint` and `token_endpoint` manually instead of using the auto-discovery, but try it that way first please.

**Comment by sapisuper** [comment]
@Askir sound good , let me try with latest update. thank you 👍

**Comment by sapisuper** [comment]
@Askir I already use latest image ghcr.io/kviklet/kviklet:main but OIDC still doesn't work. I got this error 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'kviklet.identity-provider.issuer' to java.lang.String:

    Reason: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'kviklet.identity-provider.issuer' to java.lang.String


I use this parameter 
KVIKLET_IDENTITY_PROVIDER_CLIENT_ID: [value clientId]
KVIKLET_IDENTITY_PROVIDER_CLIENT_SECRET: [value clientSecret]
KVIKLET_IDENTITY_PROVIDER_ISSUER_URI : https://[host gitlab]
KVIKLET_IDENTITY_PROVIDER_TYPE : gitlab

**Comment by Askir** [comment]
Sorry the env variable is actually `KVIKLET_IDENTITY_PROVIDER_ISSUERURI` without the last `_`. That's an error in the readme, my bad.

**Comment by sapisuper** [comment]
@Askir still not work and get different error log. 

    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [dev/kviklet/kviklet/security/IdentityProviderConfig.class]: Failed to instantiate [org.springframework.security.oauth2.client.registration.ClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception with message: null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1633) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1597) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1488) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1375) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:817) ~[spring-beans-6.0.11.jar!/:6.0.11]
	... 85 common frames omitted
    Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.ClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception with message: null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.11.jar!/:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar!/:6.0.11]
	... 101 common frames omitted
    Caused by: java.lang.NullPointerException: null
	at dev.kviklet.kviklet.security.IdentityProviderProperties.getIssuer(IdentityProviderConfig.kt:42) ~[classes!/:0.0.1-SNAPSHOT]
	at dev.kviklet.kviklet.security.IdentityProviderConfig.clientRegistrationRepository(IdentityProviderConfig.kt:68) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar!/:6.0.11]
	... 102 common frames omitted
2024-06-07T01:09:43.096067393Z

**Comment by Askir** [comment]
I got this working rather fast with using a local properties file. But indeed the environment variables are really confusing, spring doesn't really seem to allow using `_` in environment variables within a single property name. So what worked in the end was this setup:
```
KVIKLET_IDENTITYPROVIDER_CLIENTID=
KVIKLET_IDENTITYPROVIDER_CLIENTSECRET=
KVIKLET_IDENTITYPROVIDER_ISSUERURI=https://gitlab.com
KVIKLET_IDENTITYPROVIDER_TYPE=gitlab
```
Make sure to set the redirect uri to `https://[your-kviklet-host]/login/oauth2/code/gitlab`
and give the application you create access to the scopes: `openid`, `email` and `profile`

Sorry for the chaos, I'll update the documentation accordingly.

https://github.com/kviklet/kviklet/assets/10251955/47d82000-5522-4a80-852e-7a6588127acc

**Comment by Askir** [comment]
This has become a bit of a catch-all issue. I'll close it for now. The kuberntes/docker-compose exec and general shell plans  aren't cancelled, but I do have a few topics open right now. And those are a bit more closely aligned with the initial vision of database prod access. So I will focus on those.

@sapisuper If you still run into problems with SSO, feel free to also open a new issue of course. (Or comment on a closed issue, I'll still get a notification after all 😄)

**Comment by sapisuper** [comment]
@Askir nice work, let me try. thank you

**Comment by sapisuper** [comment]
@Askir I just want to update, the gitlab SSO is working smooth. thanks 👍
